controller:
  # name: mysite-ingress-controller
  # replicaCount: 1
  # service:
  #   name: mysite-ingress-controller
  #   type: LoadBalancer
  # metrics:
  #   enabled: true
  ingressClassResource:
    name: mysite-nginx
    enabled: true
    default: true
  config:
    custom-http-snippet: |
      include /etc/nginx/mysite-nginx.conf;
  extraVolumes:
    - name: mysite-nginx
      configMap:
        name: mysite-nginx-config
  extraVolumeMounts:
    - name: mysite-nginx
      mountPath: /etc/nginx/mysite-nginx.conf
      subPath: mysite-nginx.conf

