
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysite
  template:
    metadata:
      labels:
        app: mysite
    spec:
      imagePullSecrets:
        - name: docker-registry-secret
      containers:
      - name: mysite
        image: volade/mysite:latest
        ports:
        - containerPort: 3000
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: mysite-nginx-config-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: mysite-nginx-config-volume
        configMap:
          name: mysite-nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: mysite
spec:
  type: LoadBalancer
  selector:
    app: mysite
  ports:
    - name: nginx-port
      port: 80
      targetPort: 80