---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysite-app
  template:
    metadata:
      labels:
        app: mysite-app
    spec:
      imagePullSecrets:
        - name: docker-registry-secret
      containers:
      - name: mysite
        image: volade/mysite:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: mysite-svc
spec:
  type: LoadBalancer
  selector:
    app: mysite-app
  ports:
    - name: nginx-port
      port: 80
      targetPort: 80
      # nodePort: 32039

# ---

# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: mysite-ingress
#   annotations:
#     nginx.ingress.kubernetes.io/rewrite-target: /
# spec:
#   ingressClassName: mysite-nginx
#   rules:
#   - host: victorolade.com
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: mysite-svc
#             port:
#               number: 80
