---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysite-app
  template:
    metadata:
      labels:
        app: mysite-app
    spec:
      imagePullSecrets:
        - name: docker-registry-secret
      containers:
      - name: mysite
        image: volade/mysite:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: mysite-svc
spec:
  type: NodePort
  selector:
    app: mysite-app
  ports:
    - name: nginx-port
      port: 80
      targetPort: 80
      nodePort: 32039