apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysite-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysite-app
  template:
    metadata:
      labels:
        app: mysite-app
    spec:
      volumes:
      - name: shared-volume
        emptyDir: {}

      containers:
      - name: mysite-app
        image: volade/mysite:latest
        volumeMounts:
        - mountPath: /app/build
          name: shared-volume

      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: shared-volume
        - mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
          name: config-volume

      volumes:
      - name: config-volume
        configMap:
          name: mysite-nginx-config
          items:
            - key: custom-nginx.conf
              path: nginx.conf
